### ISSUE TITLE
Can I fix the issue that text issue in the box.

### ISSUE THREAD

**Issue by MRIEnan** [jaitensahu/Color_Grove#2]
@jaitensahu  Initially There should be a text in my opinion. If you have no issue can I fix it under the label of hacktoberfest.
![image](https://github.com/jaitensahu/Color_Grove/assets/73898121/5de5abef-cb74-43bd-8f96-6c773a50480c)

**Comment by jaitensahu** [comment]
Hi @MRIEnan 

Thank you for your interest in contributing to our project! We appreciate your willingness to help.
Assigning it to you.
