### ISSUE TITLE
Improve : spacing on the website 

### ISSUE THREAD

**Issue by RSMJAN** [jaitensahu/Color_Grove#4]
![Screenshot 2023-10-25 165554](https://github.com/jaitensahu/Color_Grove/assets/118245358/29eaf7db-28d1-4c20-bfdc-966fed089708)

We can improve website design by adding spacings and aligning the texts

**Comment by RSMJAN** [comment]
can I fix it under the label of hacktoberfest ?!

**Comment by jaitensahu** [comment]
@RSMJAN  Assigned it to you

**Comment by jaitensahu** [comment]
Please go through the contributing guidelines before creating a PR

**Comment by RSMJAN** [comment]
thanks, I will go through it
