### ISSUE TITLE
BUG: Change shape button doesn't work properly

### ISSUE THREAD

**Issue by Lok-ii** [jaitensahu/Color_Grove#7]
After adding some text inside the textbox, the change shape button doesn't work properly. You have to change the color of the inner shape to change the shapes again.

To check out the issue:

1. Go to the hosted link
2. type some text inside the textbox
3. try changing the shape now
4. see issue

**Comment by jaitensahu** [comment]
Thank you for bringing this issue to our attention, and we appreciate your thorough explanation. Assigned it to you.

**Comment by VirendrKumarYadav** [comment]
hey @jaitensahu  , I want to resolve this issue, 
can you assign me so that I can move Forword?.

**Comment by jaitensahu** [comment]
hii @VirendrKumarYadav  assigned this to you also. Make sure to fetch the latest update before creating a PR

**Comment by jaitensahu** [comment]
@Lok-ii and @VirendrKumarYadav any updates regarding the issue.?

**Comment by Lok-ii** [comment]
Sorry @jaitensahu, I am just seeing this, I will update you by tonight.

**Comment by Lok-ii** [comment]
@jaitensahu I have fixed the issue and created a PR. I hope it meets your expectations.
